Add minimum lines for ::std::error::Error implementation
lambda-fairy/rust-errno pull request #29
Opened 2020-10-20 22:52 UTC by chamaken

To compile below with current (1.47) rustc:

    fn f<E: ::std::error::Error>(e: E) {}
    fn main() {
        f(errnor::Errno(0));
    }

2020-10-22 07:25 UTC, lambda-fairy requested changes

2020-10-22 07:25 UTC, lambda-fairy commented on src/lib.rs
> +use std::Error;
```
error[E0432]: unresolved import `std::Error`
  --> src/lib.rs:36:5
   |
36 | use std::Error;
   |     ^^^^^-----
   |     |    |
   |     |    help: a similar name exists in the module: `error`
   |     no `Error` in the root
```

2020-10-22 14:54 UTC, chamaken commented
Sorry, for typo in commit message too. Fixed by rebase: https://github.com/chamaken/rust-errno/commit/fbff9e4652bf2d95968fab71cf1f385b1856a457

2020-10-24 08:29 UTC, lambda-fairy approved these changes

2020-10-24 08:50 UTC, merged

2020-10-24 08:50 UTC, lambda-fairy commented
Thanks!