support Errno formatting in no_std
lambda-fairy/rust-errno pull request #43
Opened 2022-04-12 12:12 UTC by A1-Triard

2022-04-12 12:24 UTC, A1-Triard commented on src/lib.rs
> +extern crate core;
There are different approaches to use bring `core` and `std` duplicates together and use them in unified way. I like this way when you import `core` crate explicitly and then use `core` prefix in both std and no_std modes. But I can rewrite it with any different approach.

2022-04-12 12:24 UTC, A1-Triard commented on src/unix.rs
> +fn from_utf8_lossy(input: &[u8]) -> &str {
This function is duplicated in `wasi.rs`. I can avoid duplication if needed.

Also, important note about this function: if `input` contains non-UTF8 compliant byte sequence, decoding will be stopped at the fist occurrence of such sequence. I can improve this behavior if needed.

2022-04-12 12:24 UTC, A1-Triard commented on src/windows.rs
> +        let mut msg_buf = [0u8; 2048];
Message could be truncated if it does not fit into this buffer (in UTF-8), but it could be truncated already so I suppose this is not critical.

2022-05-09 07:16 UTC, lambda-fairy commented
Hi @A1-Triard, sorry for the delay!

Any reason why this was closed? This looks pretty good to me.

2022-05-09 07:43 UTC, A1-Triard commented
Hi! I finally decided it would better for me to stick with my own fork. (This is not because the response delay, I have my own reasons.) That's the only reason, why it was closed.

In any case, I've reopen the request now. Please merge if you want.

2022-05-10 06:39 UTC, lambda-fairy requested changes
LGTM modulo comments

-------

Also, there's this error in CI:

```
error[E0433]: failed to resolve: use of undeclared type `CStr`
Error:   --> src/unix.rs:44:26
   |
44 |     let c_str = unsafe { CStr::from_ptr(buf.as_ptr()) };
   |                          ^^^^ use of undeclared type `CStr`

error[E0412]: cannot find type `c_char` in this scope
Error:   --> src/unix.rs:35:25
   |
35 |     let mut buf = [0 as c_char; 1024];
   |                         ^^^^^^
   |
help: a builtin type with a similar name exists
   |
35 |     let mut buf = [0 as char; 1024];
   |                         ~~~~
help: consider importing this type alias
   |
17 | use libc::c_char;
   |

error[E0425]: cannot find function `strerror_r` in this scope
Error:   --> src/unix.rs:37:12
   |
37 |         if strerror_r(err.0, buf.as_mut_ptr(), buf.len() as libc::size_t) < 0 {
   |            ^^^^^^^^^^ not found in this scope
   |
help: consider importing this function
   |
17 | use libc::strerror_r;
   |
```

2022-05-10 06:39 UTC, lambda-fairy commented on src/windows.rs
> +            return (i, unsafe { output.as_ptr().offset_from(output_start) } as usize);
This `unsafe` looks unnecessary. Can we rewrite it using safe code? Say, by keeping track of how many bytes are written so far.

2022-05-10 06:39 UTC, lambda-fairy commented on src/windows.rs
> +fn from_utf16_lossy(input: &[u16], mut output: &mut [u8]) -> (usize, usize) {
This function guarantees that the written bytes are valid UTF-8. To localize this invariant, can we have the function return a `&str` directly?

```rust
fn from_utf16_lossy<'a>(input: &[u16], output: &'a mut [u8]) -> &'a str
```

2022-05-10 06:39 UTC, lambda-fairy commented on src/lib.rs
> +extern crate core;
LGTM, thanks!

2022-05-10 06:39 UTC, lambda-fairy commented on src/unix.rs
> +fn from_utf8_lossy(input: &[u8]) -> &str {
Yeah, that's all right with me

2022-05-10 09:21 UTC, A1-Triard commented
Because I deleted the fork, I have to create a new pull request (https://github.com/lambda-fairy/rust-errno/pull/44) instead of this one. Please re-review it.

2022-05-10 09:22 UTC, closed without merging